In [1]:
fpath = 'D:/code_project/datasource/export_sql_1558435/sqlResult_1558435.csv'
from sklearn.feature_extraction.text import TfidfVectorizer
vectorized = TfidfVectorizer(max_features = 10000)

In [2]:
import pandas as pd
content = pd.read_csv(fpath,encoding='gb18030')
content.head()

id      author                  source  \
0  89617         NaN  快科技@http://www.kkj.cn/   
1  89616         NaN  快科技@http://www.kkj.cn/   
2  89615         NaN  快科技@http://www.kkj.cn/   
3  89614         NaN                     新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  
0     http://www.cnbeta.com/articles/tech/623597.htm  
1     http://www.cnbeta.com/articles/tech/623599.htm  
2     http://www.cnbeta.com/articles/tech/623601.htm  
3  http://world.huanqiu.com/hot/2017-06/10866126....  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...

筛选和分词函数

In [3]:
import jieba
import re

def token(string):
    return re.findall(r'[\d|\w]+',string)

def cut(string):
    return ' '.join(jieba.cut(string))

In [4]:
token('这是一个测试/\\\#$^&*\n\n')

['这是一个测试']

过滤有效内容+切词

In [5]:
news_content = content['content'].tolist()
news_content = [token(str(n)) for n in news_content]
news_content = [' '.join(n) for n in news_content]
news_content = [cut(n) for n in news_content]

Building prefix dict from the default dictionary ...
Dumping model to file cache C:\Users\HSUHUI~1\AppData\Local\Temp\jieba.cache
Loading model cost 2.463 seconds.
Prefix dict has been built succesfully.


In [6]:
news_content[0:2]

['此外   自 本周   6 月 12 日   起   除 小米 手机 6 等 15 款 机型 外   其余 机型 已 暂停 更新 发布   含 开发 版   体验版 内测   稳定版 暂不受 影响   以 确保 工程师 可以 集中 全部 精力 进行 系统优化 工作   有人 猜测 这 也 是 将 精力 主要 用到 MIUI   9 的 研发 之中   MIUI   8 去年 5 月 发布   距今已有 一年 有余   也 是 时候 更新换代 了   当然   关于 MIUI   9 的 确切 信息   我们 还是 等待 官方消息',
 '骁龙 835 作为 唯一 通过 Windows   10 桌面 平台 认证 的 ARM 处理器   高通 强调   不会 因为 只 考虑 性能 而 去 屏蔽掉 小 核心   相反   他们 正 联手 微软   找到 一种 适合 桌面 平台 的   兼顾 性能 和 功耗 的 完美 方案   报道 称   微软 已经 拿到 了 一些 新 的 源码   以便 Windows   10 更好 地 理解 big   little 架构   资料 显示   骁龙 835 作为 一款 集成 了 CPU   GPU   基带   蓝牙   Wi   Fi 的 SoC   比 传统 的 Wintel 方案 可以 节省 至少 30   的 PCB 空间   按计划   今年 Q4   华硕   惠普   联想 将 首发 骁龙 835   Win10 电脑   预计 均 是 二合一 形态 的 产品   当然   高通 骁龙 只是 个 开始   未来 也许 还 能 见到 三星 Exynos   联发科   华为 麒麟   小米 澎湃 等 进入 Windows   10 桌面 平台']

In [7]:
sample_num = 50000
sub_samples = news_content[:sample_num]
X = vectorized.fit_transform(sub_samples)

In [8]:
X.shape

(50000, 10000)

In [9]:
vectorized.vocabulary_ 

{'此外': 6190,
 '本周': 5888,
 '12': 35,
 '小米': 3970,
 '手机': 4873,
 '15': 46,
 '其余': 1842,
 '暂停': 5734,
 '更新': 5756,
 '发布': 2632,
 '开发': 4401,
 '影响': 4521,
 '确保': 7334,
 '工程师': 4128,
 '可以': 2731,
 '集中': 9631,
 '全部': 1741,
 '精力': 7658,
 '进行': 9140,
 '工作': 4109,
 '有人': 5804,
 '猜测': 6875,
 '主要': 912,
 '研发': 7315,
 '之中': 933,
 '去年': 2555,
 '一年': 303,
 '时候': 5624,
 '当然': 4501,
 '关于': 1817,
 '信息': 1545,
 '我们': 4797,
 '还是': 9082,
 '等待': 7603,
 '作为': 1440,
 '唯一': 2962,
 '通过': 9248,
 '10': 12,
 '平台': 4251,
 '认证': 8552,
 '处理器': 3327,
 '强调': 4477,
 '不会': 552,
 '因为': 3041,
 '考虑': 7978,
 '性能': 4637,
 '核心': 6064,
 '相反': 7208,
 '他们': 1243,
 '联手': 8019,
 '微软': 4575,
 '找到': 4944,
 '一种': 345,
 '适合': 9192,
 '兼顾': 1862,
 '完美': 3778,
 '方案': 5533,
 '报道': 5021,
 '已经': 4152,
 '拿到': 5087,
 '一些': 254,
 '以便': 1260,
 '更好': 5753,
 '理解': 6961,
 '架构': 6018,
 '资料': 8791,
 '显示': 5699,
 '一款': 333,
 '集成': 9638,
 '传统': 1356,
 '节省': 8200,
 '至少': 8131,
 '30': 103,
 '空间': 7494,
 '按计划': 5119,
 '今年': 1218,
 '联想': 8018,
 '首发': 982

文本进行TDIDF的文本向量化后，得到的是稀疏矩阵。
+ 要将稀疏矩阵显示出来，用方法： toarray()

In [75]:
import numpy as np
np.where(X[0].toarray()[0])  # get the positions which values are not zero

(array([  35,   46,  303,  912,  933, 1545, 1741, 1817, 1842, 2555, 2632,
        2731, 3970, 4109, 4128, 4401, 4501, 4521, 4797, 4873, 5624, 5734,
        5756, 5804, 5888, 6190, 6875, 7315, 7334, 7603, 7658, 9082, 9140,
        9631], dtype=int64),)

In [73]:
a = np.array([1,0,1,1,2,0,0,0,1,6])
np.where(a)

(array([0, 2, 3, 4, 8, 9], dtype=int64),)

In [74]:
np.where(a)[0]

array([0, 2, 3, 4, 8, 9], dtype=int64)

In [14]:
news_content[0]

'此外   自 本周   6 月 12 日   起   除 小米 手机 6 等 15 款 机型 外   其余 机型 已 暂停 更新 发布   含 开发 版   体验版 内测   稳定版 暂不受 影响   以 确保 工程师 可以 集中 全部 精力 进行 系统优化 工作   有人 猜测 这 也 是 将 精力 主要 用到 MIUI   9 的 研发 之中   MIUI   8 去年 5 月 发布   距今已有 一年 有余   也 是 时候 更新换代 了   当然   关于 MIUI   9 的 确切 信息   我们 还是 等待 官方消息'

In [24]:
import random
document_id_1, document_id_2 = random.randint(0,5000), random.randint(0,5000)
print(document_id_1,document_id_2)

2103 912


In [25]:
vector_of_d_2 = X[document_id_2].toarray()
np.where(vector_of_d_2)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0], dtype=int64),
 array([  12,   64,  214,  274,  293,  348,  374,  440,  459,  508,  567,
         582,  607,  627,  633,  659,  661,  706,  720,  938,  955, 1002,
        1135, 1207, 1243, 1441, 1457, 1458, 1604, 1608, 1762, 1817, 1840,
        1998, 2050, 2126, 2172, 2277, 2337, 2431, 2447, 2516, 2533, 2596,
        2727, 2731, 2797, 2805, 2898, 2965, 2967, 3041, 3043, 3591, 3649,
        3653, 3771, 3849, 3942, 4203, 4293, 4527, 4602, 4703, 4779, 4806,
        4912, 4923, 5109, 5151, 5226, 5309, 5325, 5429, 5439, 5645, 

In [62]:
X[document_id_2].toarray()

array([[0., 0., 0., ..., 0., 0., 0.]])

我们能够得到每一篇文章的TFIDF向量，然后知道在每一篇文章中，哪些单词的位置不为0（也就说，知道有哪些单词在文章中）。

In [26]:
random_choice = random.randint(0,50000)
random_choice

46692

向量cosine距离函数

In [61]:
from scipy.spatial.distance import cosine
def distance(v1, v2):
    return cosine(v1, v2)

distance(X[random_choice].toarray()[0], X[document_id_1].toarray()[0])

0.9837202683904289

In [28]:
distance(X[random_choice].toarray()[0], X[document_id_2].toarray()[0])

0.9935119891935761

In [34]:
news_content[document_id_1]

'环球网 综合 报道   据 法国   费加罗 报   报道   不少 考生 为了 增强 记忆力 会 服用 药物   但 要 当心   某些 使人 兴奋 的 物质 也 会 降低 专注 力   报道 称   每逢 大考 就 有 不少 人到 药店 寻找   吃 了 能 让 人学 得 更 快 更好   的 药   各大 厂家 甚至 5 月初 就 开始 上市 各类 助考 胶囊剂   一名 药剂师 幽默 地 说道   来 买药 的 通常 是 父母   他们 比 孩子 还 焦虑   他开 在 南特 的 药房 里   以 人参 和 红景天 为 主要 成分 的 产品 的 销量 比以 咖啡 因为 主要 成分 的 克劳 酸 销量 还好   因为 据说 人参 和 红景天 更能 缓解 疲劳   提高 专注 力   除此之外   所有 含有 维生素 和 矿物质 的 药品 销量 都 很 不错   其本质 和 顺势 疗法 一样   考前 服药 以期 缓解 焦虑   大脑 与 骨髓 研究院 的 科学 主任 贝特 朗   方丹   Bertrand   Fontaine   强调   目前 没有 任何 一种 药物 被 证明 对 增强 记忆力 有 特效   至于 服用 人参 和 克劳 酸 等 可 使 人 兴奋 的 产品 非但 不会 增强 记忆力   反而 会 降低 专注 力   时 也 要 注意   某些 精神药品   如 安眠药   安定 药   的 说明书 上 明确 写 着 服用 本品 会 降低 记忆力   至于 焦虑   除非 极端 情况 可以 使用 beta 受体 阻断 药外   通常 情况 下 没有 特效药   方丹称   药房 能开 的 药 只能 缓解 紧张 的 症状   如 心跳 过快   出汗   脸红 等   都 属于 焦虑 已经 出现 明显 症状 时 服用 的 药   此外   方丹 指出   关于 大脑 表现   唯一 能 让 大脑 更 高效 地 记忆 信息 的 方法 就是 睡眠   所以 复习 到 凌晨 两点 还 不如 每天 按时 作息   饮食   否则 还 可能 得 低血糖   实习 编译   唐科   审稿   赵怡蓁'

In [32]:
news_content[document_id_2]

'北京 时间 6 月 20 日 晚间 路透 消息   苹果公司 扩大 了 对 高通 的 指控   该 公司 向 美国联邦 法院 表示   高 通向 每台 iPhone 都 索求 的 专利 授权 费是 完全 不合理 的   如果 法庭 裁决 苹果 的 指控 成功   高通 整个 商业模式 的 核心 原则 将会 动摇   苹果公司 1 月份 起诉 高通   因为 苹果 配合 韩国 监管 机构 调查 高通   该 芯片 制造商 非法 扣除 了 苹果 10 亿美元 的 回扣   苹果 最初 的 诉讼 目标 较为 狭隘   专注 于 苹果 配合 监管 机构 调查 高通公司 的 业务 是否 违反 双方 的 商业 合同   但 在 新 的 指控 文件 中 苹果 扩大 了 起诉 范围   试图 通过 上个月 通过 的 法律 理论 彻底 破坏 高通 的 长期 业务 模式   美国最高法院 上 月 对 一家 打印机 与 另一家 转售 其 墨盒 公司 之间 的 专利 纠纷 作出 裁决   判决 结果 使得 制造商 和 药品 公司 更难 管控 他们 的 产品 如何 使用 或 转售   路透社 的 周二 简报 透露   苹果公司 针对 的 正是 高通公司 要求 其 客户 采购 芯片 之前 必须 签署 专利 许可 协议 的 做法   高通 这一 做法 被 业内 称为   无 许可   无 芯片   正 由于 此项 条款   因 使用 了 高通 所产 的 调频 芯片   苹果 每 卖出 一部 iPhone 都 要 付给 高通 相应 的 专利 授权 费   苹果 认为   上述 关于 两家 打印机 公司 专利 纠纷 的 裁决 说明   高通公司 因 自己 的 知识产权 和 产品 只能 获得   一笔 奖励   苹果 还 表示   高通 可以 收取 专利 许可费 或者 出售 芯片 的 费用   但 不能 两者 都 收费   因此 苹果 希望 能够 在 不 签署 专利 许可 协议 的 情况 下 购买 芯片   这 使得 该 公司 可以 避免 每 卖出 一台 iPhone 都 不得不 分成 给 高通   苹果 还 要求 法院 停止 高 通向 富士康 科技 集团 和 其他 三家 合约 制造商 提起 诉讼   这些 厂商 均 是 iPhone 的 代工厂   并且 是 高通 芯片 的 正式 买家   编译 

In [33]:
news_content[random_choice]

'为了 让 更 多 人能 愉快 地 度过 五一劳动节 假期   总有 这样 一群 人   他们 默默地 坚守 在 岗位 上 辛勤 奉献   下面 就让 我们 认识 几位 劳动者   感受 他们 的 最美 五一节   n 记者   李爱斌   何山   孙蕾   邵香云   李帅   冯忻   n 视频 编辑   刘媛媛   n 编辑   董劭   n 中国 新华 新闻 电视网   n'

排序

In [37]:
def distance_with_choice(i):
    return distance(X[random_choice].toarray()[0], X[i].toarray()[0])

In [39]:
sorted(list(range(100)), key=distance_with_choice)

[48,
 52,
 73,
 64,
 22,
 8,
 4,
 42,
 86,
 96,
 54,
 41,
 81,
 71,
 85,
 98,
 37,
 26,
 79,
 1,
 46,
 60,
 27,
 14,
 58,
 38,
 61,
 56,
 11,
 70,
 36,
 83,
 0,
 66,
 80,
 6,
 62,
 5,
 7,
 21,
 49,
 30,
 17,
 88,
 97,
 12,
 95,
 45,
 33,
 3,
 39,
 91,
 67,
 69,
 13,
 29,
 31,
 65,
 15,
 63,
 47,
 68,
 20,
 89,
 51,
 90,
 93,
 44,
 53,
 84,
 59,
 19,
 55,
 57,
 99,
 72,
 40,
 77,
 78,
 2,
 9,
 10,
 16,
 18,
 23,
 24,
 25,
 28,
 32,
 34,
 35,
 43,
 50,
 74,
 75,
 76,
 82,
 87,
 92,
 94]

In [41]:
news_content[48][:500]

'吐尔孙   艾拜   我 叫 吐尔孙   艾拜   最近 看到 很多 优秀 的 维吾尔族 青年 在 网络   微信   博客 上 的 发声 文章   我 也 想 和 大家 分享 一些 我 的 故事 和 看法   我 出生 在 一个 不太 富裕 的 家庭   父亲 是 银行职员   他 去世 的 时候 我 和 弟弟 还 在 上 小学   那 之后 生活 的 重担 便 全落 在 没有 工作 的 母亲 身上   初中 毕业 后 为了 尽快 工作   我 考入 莎车 师范学校   但是 毕业 后 找 不到 工作   希望 就此 落空   母亲 不忍 看到 我 的 失落   便 把 我 送到 县 高三 复习班 备考 大学   这 是 我 人生 中 最 难忘 的 一年   为了 备考   早晨 天 还 没有 亮 我 就 起床 早读   晚上 吃完饭 就 看书   有时 半夜 醒来 发现 趴在 书上 灯 还 亮 着   功夫不负有心人   2003 年 我 参加 高考 并 被 复旦大学 录取   2009 年 又 考上 清华大学 的 硕士 研究生   毕业 后 进入 乌鲁木齐市 达坂城区 工作   '

# Build Search Engine
+ Input: words
+ Out: Document

In [42]:
# test
[i % 2 == 0 for i in [1,2,3,4,5,6]]

[False, True, False, True, False, True]

In [43]:
any([i % 2 == 0 for i in [1,2,3,4,5,6]])

True

In [44]:
def naive_search(keywords):
    news_ids = [i for i,n in enumerate(news_content) if all(w in n for w in keywords)]
    # 复杂度O（D * w * document_length）
    return news_ids

In [49]:
%%timeit
keywords_list = '美军 司令 航母'.split()
ids = naive_search(keywords= keywords_list)

101 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [52]:
keywords_list = '美军 司令 航母'.split()
ids = naive_search(keywords= keywords_list)
ids

[2844,
 21484,
 21523,
 21784,
 21901,
 22987,
 33522,
 33770,
 34532,
 34887,
 37846,
 38049,
 38096,
 45474,
 45507,
 87483,
 88997]

### Input word --> id of the documents which contain these words
以上的搜索方法是：输入词汇列表，搜索包含这些词汇的文档，并返回文档的id

# Boolean search

+ X是我们的tfidf向量矩阵。
+ 每一行代表的是该文章中每个单词的tfidf值。
+ 矩阵转置之后，每一行代表该单词在文章中出现的情况。

In [87]:
transposed_x = X.transpose().toarray()

In [88]:
word_2_id = vectorized.vocabulary_

In [89]:
id_2_word = {id:w for w,id in word_2_id.items()}

In [90]:
id_2_word[999]

'书香'

In [91]:
np.where(transposed_x[999])

(array([ 5577,  6214,  6470,  7029,  7298,  7326,  7440, 10052, 11463,
        11856, 12819, 13396, 13397, 13452, 14977, 15130, 15377, 16357,
        16509, 16528, 16899, 16983, 21079, 21080, 21082, 24322, 24656,
        24703, 29436, 29438, 29440, 29649, 29675, 30599, 32545, 32640,
        33729, 33731, 33856, 35086, 35090, 35206, 35307, 35309, 35310,
        35992, 35995, 35998, 36012, 36100, 36102, 36108, 36294, 36299,
        36301, 36377, 36378, 36379, 36380, 36381, 36382, 36383, 36384,
        36385, 36386, 36387, 36391, 36537, 36586, 36587, 36635, 36680,
        36704, 36705, 37248, 37249, 37250, 37300, 37302, 37308, 37309,
        37454, 37536, 37629, 37630, 37634, 37635, 37636, 37637, 37638,
        37641, 37643, 37644, 37646, 37745, 37746, 37747, 37822, 37823,
        37827, 37828, 37833, 37838, 38120, 38330, 38366, 38367, 38368,
        38415, 38440, 38485, 38526, 38674, 38676, 38679, 38680, 38681,
        38682, 38683, 38684, 38685, 38686, 38687, 38688, 38689, 38690,
      

In [81]:
from functools import reduce
from operator import and_

d1, d2, d3 = {1,2,3}, {3,4,5,6}, {1,3,5}
reduce(and_, [d1,d2,d3])

{3}

基于向量的搜索引擎

In [97]:
def search_engine(query):
    """
    @query is the search words, splited by space
    @return is the related ducuments which ranked by tfidf similarity
    """
    words = query.split()
    query_vectory = vectorized.transform([' '.join(words)]).toarray()[0]
    words_ids = [word_2_id[w] for w in words]
    documents_ids = [set(np.where(transposed_x[id_])[0]) for id_ in words_ids]
    merged_documents = reduce(and_, documents_ids)
    # we could know the documents which contain these words
    sorted_documents_ids = sorted(merged_documents, key=lambda i:distance(query_vectory, X[i].toarray()))
    return sorted_documents_ids

In [98]:
distance([1,1],[[2,2]])

0.0

In [107]:
%%time
search_engine('美军 司令 航母')

Wall time: 16 ms


[22987, 21523, 21484, 2844]

高亮文本，如下：
* 将搜索到的文章中，关键字高亮

In [108]:
text = """新华社洛杉矶４月８日电（记者黄恒）美国第三舰队８日发布声明说，该舰队下属的“卡尔·文森”航母战斗群当天离开新加坡，改变原定驶往澳大利亚的任务计划，转而北上，前往西太平洋朝鲜半岛附近水域展开行动。\n　　该舰队网站主页发布的消息说，美军太平洋司令部司令哈里·哈里斯指示“卡尔·文森”航母战斗群向北航行。这一战斗群包括“卡尔·文森”号航空母舰、海军第二航空队、两艘“阿利·伯克”级导弹驱逐舰和一艘“泰孔德罗加”级导弹巡洋舰。\n　　“卡尔·文森”号航母的母港位于美国加利福尼亚州的圣迭戈，今年１月初前往西太平洋地区执行任务，并参与了日本及韩国的军事演习。\n　　美国有线电视新闻网援引美国军方官员的话说，“‘卡尔·文森’号此次行动是为了对近期朝鲜的挑衅行为作出回应”。（完）"""
print(text)

新华社洛杉矶４月８日电（记者黄恒）美国第三舰队８日发布声明说，该舰队下属的“卡尔·文森”航母战斗群当天离开新加坡，改变原定驶往澳大利亚的任务计划，转而北上，前往西太平洋朝鲜半岛附近水域展开行动。
　　该舰队网站主页发布的消息说，美军太平洋司令部司令哈里·哈里斯指示“卡尔·文森”航母战斗群向北航行。这一战斗群包括“卡尔·文森”号航空母舰、海军第二航空队、两艘“阿利·伯克”级导弹驱逐舰和一艘“泰孔德罗加”级导弹巡洋舰。
　　“卡尔·文森”号航母的母港位于美国加利福尼亚州的圣迭戈，今年１月初前往西太平洋地区执行任务，并参与了日本及韩国的军事演习。
　　美国有线电视新闻网援引美国军方官员的话说，“‘卡尔·文森’号此次行动是为了对近期朝鲜的挑衅行为作出回应”。（完）


In [116]:
import re
pat = r'(新闻|官员)'
pat = re.compile(pat)
pat.sub(repl='**\g<1>**', string=text)

'新华社洛杉矶４月８日电（记者黄恒）美国第三舰队８日发布声明说，该舰队下属的“卡尔·文森”航母战斗群当天离开新加坡，改变原定驶往澳大利亚的任务计划，转而北上，前往西太平洋朝鲜半岛附近水域展开行动。\n\u3000\u3000该舰队网站主页发布的消息说，美军太平洋司令部司令哈里·哈里斯指示“卡尔·文森”航母战斗群向北航行。这一战斗群包括“卡尔·文森”号航空母舰、海军第二航空队、两艘“阿利·伯克”级导弹驱逐舰和一艘“泰孔德罗加”级导弹巡洋舰。\n\u3000\u3000“卡尔·文森”号航母的母港位于美国加利福尼亚州的圣迭戈，今年１月初前往西太平洋地区执行任务，并参与了日本及韩国的军事演习。\n\u3000\u3000美国有线电视**新闻**网援引美国军方**官员**的话说，“‘卡尔·文森’号此次行动是为了对近期朝鲜的挑衅行为作出回应”。（完）'

In [117]:
def get_query_pat(query):
    return re.compile('({})'.format('|'.join(query.split())))

In [118]:
get_query_pat('美军 司令 航母')

re.compile(r'(美军|司令|航母)', re.UNICODE)

In [119]:
def highlight_keywords(pat, document):
    return pat.sub(repl='***\g<1>***', string=document)

In [124]:
highlight_keywords(pat=get_query_pat('清华 大学'), document=content['content'][11430])

'\\n新华社武汉３月３１日新媒体专电题：醒醒！***清华***毕业“硬杠杠”告诉你只顾埋头拼分不行了\\n新华社记者\\n“旱鸭子”将出不了***清华******大学***的门。对这样的规定你是“点赞”还是“吐槽”？\\n绝大多数人“点赞”，也有一些人提出疑问。无论是“点赞”还是疑问，大家忧虑的都是学生体质下滑的现状，希望综合素质教育早日能真正实现。\\n***清华***出新规逼“旱鸭子”下水\\n近日，***清华******大学***出台新规，从２０１７级本科新生开始，必须通过入学后的游泳测试或参加游泳课学习并达到要求，否则不能获得毕业证书（特殊情况除外）。\\n在***清华***的历史上，也出现过“不会游泳不能毕业”的规定。１９１９年，学校曾提出“不会游泳不能毕业赴美”的要求。上世纪９０年代末，学校提出***清华***学生“至少能游５０米以上”，还专门为二年级学生开设游泳课。但将“不会游泳不能毕业”写入学生手册作为硬性要求，尚属首次。\\n为什么挑游泳作为考查项目？***清华******大学***体育部负责人刘波解释说：“游泳是一项终身运动，有很好的锻炼效果，又是必备的生存技能，我们希望借此改变***清华***学生体质健康状况下滑的趋势。”\\n“不会游泳不能毕业”被认为是努力提升***大学***生体质、恢复***清华******大学***体育传统之举，多数受访学生对此项新规表示支持。***清华******大学***公共管理学院学生王珂说：“我们经常说‘无体育、不***清华***’，新规会鼓励更多同学投入体育锻炼，感受运动之美。”\\n也有一些人认为让所有学生都学会游泳，有些“不近人情”。对此，***清华******大学***称，如果学生确实存在因慢性病、皮肤病或心理疾病等原因不适合学习游泳的情况，递交医院等相关证明，经学校教务和体育部审核确认后，可用其他体育课程替代游泳。\\n这种“硬杠杠”非***清华***专属\\n类似的“硬杠杠”并非***清华******大学***专属。２０１１年开始，厦门***大学***将游泳作为本科生必修课，占１个学分，男生连续游１００米或女生连续游５０米为考试通过，才能获学分。２０１３年，中国人民***大学***体育部配合学校实施新的人才培养路线图，将“一拳一泳”——太极拳和游泳作为核心必修课程。\\n上海***大学***也规定本

在markdown中显示高亮

In [125]:
from IPython.display import display, Markdown

In [126]:
display(Markdown(
"""
## 标题
> 测试
+ 1
+ 2
"""
))


## 标题
> 测试
+ 1
+ 2


In [132]:
def search_engine_with_pretty_print(query):
    candidates_ids = search_engine(query=query)
    for i, _id in enumerate(candidates_ids):
        title = '## Search Result {}'.format(i+1)
        c = news_content[_id]
        c = highlight_keywords(pat=get_query_pat(query=query),document=c)
        display(Markdown(title + '\n' + c))

In [133]:
search_engine_with_pretty_print('美军 航母 司令')

## Search Result 1
新华社 北京 ４ 月 １ ０ 日电 新闻分析   卡尔   文森   号 ***航母*** 缘何 成 西太平洋 军情 新 主角   n   新华社 记者 刘莉莉   n   美国 海军 第三 舰队 下属 的   卡尔   文森   号 ***航母*** 打击 群 即将 抵达 西太平洋 朝鲜半岛 附近 水域   分析 人士 认为   美方 此次 急调 ***航母*** 打击 群 北上   向 朝鲜 施压 意图 明显   很 可能 会 加剧 朝鲜半岛 紧张局势   n   小标题   侧重 对 地 攻击   n   据 第三 舰队 网站 主页 发布 的 消息   ***美军*** 太平洋 ***司令***部 ***司令*** 哈里   哈里斯 指示   卡尔   文森   号 ***航母*** 打击 群从 新加坡 向北 航行   这一 打击 群 还 包括 海军 第二 航空队   两艘   阿利   伯克   级 导弹 驱逐舰 和 一艘   泰孔 德罗 加   级 导弹 巡洋舰   n   卡尔   文森   号 是   尼米兹   级 核动力 ***航母***   母港 位于 美国 加利福尼亚州 的 圣迭戈   今年 １ 月初   卡尔   文森   号 曾 前往 西太平洋地区 执行 任务   并 参与 美日韩 三国 军事演习   尼米兹   级 ***航母*** 是 核动力 多用途 ***航母***   也 是 美国 海军 远洋 作战 群 的 核心 力量   n   卡尔   文森   ***航母*** 打击 群中   阿利   伯克   级 导弹 驱逐舰 和   泰孔 德罗 加   级 导弹 巡洋舰 也 不可 小视   阿利   伯克   级 导弹 驱逐舰 是 世界 上 最先 配备 四面 相控阵 雷达 的 驱逐舰   舰队 防空 是 其 主要 作战 任务   泰孔 德罗 加   级 导弹 巡洋舰 的 武器 配备 也 比较 全面   涵盖 了 反潜   反舰   防空 和 对 地 ４ 个 种类   n   据 军事 专业人士 介绍   ***航母*** 打击 群 与 ***航母*** 战斗群 其实 是 两个 概念   战斗群 侧重于 夺取 制海权   例如 海战   而 ***航母*** 打击 群 更 侧重于 对 地 攻击 作战   一般而言   打击 群 的 舰艇 数量 要远 少于 战斗群   n   小标题   配角 跻身 主角   n   第三 舰队 是 美国 海军 太平洋 舰队 两大 舰队 之一   拥有 ４ 个 ***航母*** 打击 群   分别 是 以   卡尔   文森   号 为 核心 的 第一 ***航母*** 打击 群   以   约翰   斯坦尼斯   号 为 核心 的 第三 ***航母*** 打击 群   以   西奥多   罗斯福   号 为 核心 的 第九 ***航母*** 打击 群和以   尼米兹   号 为 核心 的 第十一 ***航母*** 打击 群   n   资深 军事 评论员 石宏说   在 美国 海军 力量 中   第三 舰队 原本 地位 一般   因为 其所 管辖 的 国际日期变更线 以东 的 东 太平洋 比较 安稳   所以 更 多 扮演 战略 预备队 的 配角 角色   只有 在 负责 执行 前沿 部署 和 应急 反应 任务 的 第七 舰队 有 需要 时   第三 舰队 才 会 奉令 前去 换班 或 增援   但 自 ２ ０ １ ５ 年 下半年 以来   太平洋 舰队 打破 了 延续 数十年 的 惯例   大幅 提升 第三 舰队 的 活跃度   令其 开始 更 多 涉足 西太平洋地区   n   实际上   这是 ***美军*** 根据 新 的   全球 一体化   军事战略 而 做 的 调整   目的 是 优化 资源   改变 本土 与 前沿 的 兵力 平衡   缓解 目前 美国 海军 兵力 不足 与 战线 过长   资源 下滑 与 保持 战备 之间 的 尖锐 矛盾   石宏说   n   正因如此   卡尔   文森   号 ***航母*** 开始 忙碌 起来   自从 今年 １ 月 离开 母港 后   卡尔   文森   号边 走 边练   特别 是 在 夏威夷 和 关岛 水域 与 当地 驻扎 部队 进行 了 多 轮演 训   ２ 月 １ ８ 日   卡尔   文森   号 ***航母*** 进入 南海 水域 进行 所谓   巡航   ３ 月 １ ５ 日   卡尔   文森   号 抵达 韩国 釜山   随后 在 ２ ０ 日 参加 了 美韩   关键 决断   联合 军演   ４ 月 ４ 日   卡尔   文森   号 抵达 新加坡   原本 计划 南下 前往 澳大利亚   但 随后 接到 再度 北上 命令   赶往 朝鲜半岛 附近 海域   n   小标题   或 在 火上浇油   n   一名 不愿 公开 姓名 的 五角大楼 官员 告诉 美国有线电视新闻网   卡尔   文森   号 ***航母*** 打击 群 驶向 西太平洋 的 朝鲜半岛 水域   旨在 对 近期 朝鲜 的 挑衅 行为 作出 回应   n   包括   卡尔   文森   号 在内 的 美国 海军 新近 动向 引起 各方 关注   不少 人 担心   这一 行动 将 给 半岛 紧张局势 火上浇油   俄罗斯 议会上院 防务 和 安全 委员会 主席 维克托   奥泽罗夫 警告 说   美国 动作 可能 会 刺激 朝鲜 方面 作出 急躁 反应   n   石宏 认为   美国 急调   卡尔   文森   号 ***航母*** 打击 群 赶赴 半岛 附近 水域   是 想 通过 军事 施压   迫使 朝鲜 放弃 进行 新一轮 核试验 的 打算   但 从 以往 经验 看   美国 用 不断 加码 的 军事 威慑 不仅 不会 让 半岛 局势 降温   反而 会 刺激 朝鲜 越发 强硬   完

## Search Result 2
n 新华社 洛杉矶 4 月 8 日新 媒体 专电   记者 黄恒   美国 第三 舰队 8 日 发布 声明 说   该 舰队 下属 的   卡尔   文森   ***航母*** 战斗群 当天 离开 新加坡   改变 原定 驶往 澳大利亚 的 任务 计划   转而 北上   前往 西太平洋 朝鲜半岛 附近 水域 展开 行动   n 该 舰队 网站 主页 发布 的 消息 说   ***美军*** 太平洋 ***司令***部 ***司令*** 哈里   哈里斯 指示   卡尔   文森   ***航母*** 战斗群 向北 航行   这一 战斗群 包括   卡尔   文森   号 航空母舰   海军 第二 航空队   两艘   阿利   伯克   级 导弹 驱逐舰 和 一艘   泰孔 德罗 加   级 导弹 巡洋舰   n   n   n   3 月 14 日   在 韩国 东部 海域 举行 的 韩美 联合 军演 期间   美国 海军 人员 站 在   卡尔   文森   号 核动力 ***航母*** 上 的 一架 C   2 舰载 运输机 旁   新华社   法新   n   n   卡尔   文森   号 ***航母*** 的 母港 位于 美国 加利福尼亚州 的 圣迭戈   今年 1 月初 前往 西太平洋地区 执行 任务   并 参与 了 日本 及 韩国 的 军事演习   美国有线电视新闻网 援引 美国 军方 官员 的话 说   卡尔   文森   号 此次 行动 是 为了 对 近期 朝鲜 的 挑衅 行为 作出 回应   n

## Search Result 3
新华社 洛杉矶 ４ 月 ８ 日电   记者 黄恒   美国 第三 舰队 ８ 日 发布 声明 说   该 舰队 下属 的   卡尔   文森   ***航母*** 战斗群 当天 离开 新加坡   改变 原定 驶往 澳大利亚 的 任务 计划   转而 北上   前往 西太平洋 朝鲜半岛 附近 水域 展开 行动   n   该 舰队 网站 主页 发布 的 消息 说   ***美军*** 太平洋 ***司令***部 ***司令*** 哈里   哈里斯 指示   卡尔   文森   ***航母*** 战斗群 向北 航行   这一 战斗群 包括   卡尔   文森   号 航空母舰   海军 第二 航空队   两艘   阿利   伯克   级 导弹 驱逐舰 和 一艘   泰孔 德罗 加   级 导弹 巡洋舰   n   卡尔   文森   号 ***航母*** 的 母港 位于 美国 加利福尼亚州 的 圣迭戈   今年 １ 月初 前往 西太平洋地区 执行 任务   并 参与 了 日本 及 韩国 的 军事演习   n   美国有线电视新闻网 援引 美国 军方 官员 的话 说   卡尔   文森   号 此次 行动 是 为了 对 近期 朝鲜 的 挑衅 行为 作出 回应   完

## Search Result 4
参考消息 网 6 月 15 日 报道   日本   每日 新闻   6 月 14 日 发表 题为   日本 欲 邀请 海外 大学 和 科研机构 参与 本国 防卫 研究   的 报道 称   关于 从 大学 等 公开 招募 可 应用 于 防卫 装备 品 的 尖端 研究   并 支付 研究 委托 费 的   安全 保障 技术 研究 推进 制度   防卫 装备 厅 已 开始 研究 与 国际 制度 接轨   设想 是   将 委托 对象 从 目前 的 只限 国内   扩大 至 海外 的 大学 和 企业   该 制度 被 很多 人 批评 是   用于 军事 研究   作为 科学家 代表 机构 的 日本 学术会议 3 月 发表声明 指出   从 学术 健康 发展 角度看   存在 很多 问题   防卫 装备 厅 的 方针 料想 将会 引起 轩然大波   该 制度 中   公开 招募 的 规定 是   研究 代表人 需要 是 日本 国籍   对象 限定 为 大学   研究 机构   企业   然而   防卫 装备 厅 认为   要 想 维持 和 提高 与 安全 保障 有关 的 技术 的 优势   需要 招募 更 广泛 的 尖端 研究 机构   因此   防卫 装备 厅 准备 参考 ***美军*** 向 海外 研究者 提供 研究 资金 的 制度   并 考虑 与 美国 等 盟国 建立 共同 资金 制度   日本 防卫 装备 厅 防卫 技术 总监 外园 博一 13 日 在 千叶县 海洋 领域 国际 装备 展销会 上 发表 演讲   面对 各国 军人 和 军工企业 相关 人士 表示   希望 发展 制度   使 其 能够 国际性 地 提供 资金   反对 军事 研究 的 名古屋 大学 宇宙 物理学 名誉教授 池内 了 批评 说   到底 要 模仿 美国 到 何时   感觉 这是 通过 集体 自卫权 推进 与 盟国 一体化 的 一环   是 旨在 实现 装备 品 共同开发 的 危险 动向   原 海上 自卫队 自卫 舰队 ***司令*** 香田洋 二 表示   技术 的 问题 在于 如何 使用   从 海外 公开 招募 研究 不 存在 国家 利益 上 的 问题   但 在 现行制度 的 预算 规模 和 框架 下   海外 知名 大学 不会 满意   应该 不会 应招   点击 图片 进入 下 一页   6 月 1 日   美海军 2 艘 尼米兹 级 核 ***航母***   卡尔   文森   号   CVN   70   和   罗纳德   里根   号   CVN   76   携 数艘 提 康德罗 加级 导弹 巡洋舰 及伯克级 导弹 驱逐舰 与 日本 海上 自卫队   日向   号 直升机 ***航母*** 在 日本海 组成 庞大 编队 巡航   图为 三 ***航母*** 特 写照   从近 至 远 依次 为   文森   号   日向   号 和   里根   号